"""
AdamOps Studio — Pipeline-to-Python Compiler

Converts a visual node graph (DAG) into an executable Python script
using Jinja2 templates, preserving the flow, parameters, and variable references.
"""

from typing import Dict, List, Optional
import json
import jinja2

from adamops.studio.engine import _topological_sort, _resolve_inputs, PipelineError
from adamops.studio.nodes import get_node_type

# ── Jinja2 Templates ──────────────────────────────────────────────────

BASE_TEMPLATE = """\
\"\"\"
Generated by AdamOps Studio Compiler
\"\"\"

import pandas as pd
import numpy as np

# --- AdamOps Imports ---
from adamops.data.loaders import load_csv, load_excel, load_json
from adamops.data.preprocessors import handle_missing, handle_outliers, handle_duplicates
from adamops.data.feature_engineering import encode, scale, select_features
from adamops.data.splitters import split_train_test, split_train_val_test
from adamops.models.modelops import train
from adamops.models.automl import run as run_automl
from adamops.evaluation.metrics import evaluate

def main():
    print("🚀 Starting AdamOps Pipeline Execution...")
    
{{ code_blocks }}
    
    print("✅ Pipeline execution completed successfully.")
    return locals()

if __name__ == "__main__":
    results = main()
"""

# Mapping of node_type_id -> Jinja2 snippet
# Snippets bind `node_id`, `params`, and `inputs` (which contains `{port_name: var_name}`)
# into Python instructions, emitting output into localized variable names (`{node_id}_{port_name}`).
NODE_TEMPLATES = {
    # Data Nodes
    "load_csv": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = load_csv("{{ params.filepath }}")\
""",
    "load_excel": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = load_excel("{{ params.filepath }}", sheet_name="{{ params.sheet_name }}")\
""",
    "load_json": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = load_json("{{ params.filepath }}")\
""",

    # Preprocessing Nodes
    "handle_missing": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = handle_missing({{ inputs.dataframe }}, strategy="{{ params.strategy }}")\
""",
    "handle_outliers": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = handle_outliers({{ inputs.dataframe }}, method="{{ params.method }}", threshold={{ params.threshold }})\
""",
    "handle_duplicates": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = handle_duplicates({{ inputs.dataframe }})\
""",

    # Feature Engineering Nodes
    "encode": """\
    # {{ node_label }} ({{ node_id }})
    {%- if params.columns %}
    {{ node_id }}_columns = [c.strip() for c in "{{ params.columns }}".split(",") if c.strip()]
    {{ node_id }}_dataframe = encode({{ inputs.dataframe }}, columns={{ node_id }}_columns, method="{{ params.method }}")
    {%- else %}
    {{ node_id }}_cat_cols = {{ inputs.dataframe }}.select_dtypes(include=["object", "category"]).columns.tolist()
    if {{ node_id }}_cat_cols:
        {{ node_id }}_dataframe = encode({{ inputs.dataframe }}, columns={{ node_id }}_cat_cols, method="{{ params.method }}")
    else:
        {{ node_id }}_dataframe = {{ inputs.dataframe }}
    {%- endif %}
""",
    "scale": """\
    # {{ node_label }} ({{ node_id }})
    {%- if params.columns %}
    {{ node_id }}_columns = [c.strip() for c in "{{ params.columns }}".split(",") if c.strip()]
    {{ node_id }}_dataframe = scale({{ inputs.dataframe }}, method="{{ params.method }}", columns={{ node_id }}_columns)
    {%- else %}
    {{ node_id }}_dataframe = scale({{ inputs.dataframe }}, method="{{ params.method }}")
    {%- endif %}
""",
    "select_features": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_dataframe = select_features({{ inputs.dataframe }}, target="{{ params.target }}", method="{{ params.method }}", n_features={{ params.n_features }})\
""",

    # Splitting Nodes
    "train_test_split": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_X = {{ inputs.dataframe }}.drop(columns=["{{ params.target }}"])
    {{ node_id }}_y = {{ inputs.dataframe }}["{{ params.target }}"]
    {{ node_id }}_X_train, {{ node_id }}_X_test, {{ node_id }}_y_train, {{ node_id }}_y_test = split_train_test(
        {{ node_id }}_X, {{ node_id }}_y, test_size={{ params.test_size }}
    )\
""",
    "train_val_test_split": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_X = {{ inputs.dataframe }}.drop(columns=["{{ params.target }}"])
    {{ node_id }}_y = {{ inputs.dataframe }}["{{ params.target }}"]
    {{ node_id }}_split_res = split_train_val_test(
        {{ node_id }}_X, {{ node_id }}_y, train_size={{ params.train_size }}, val_size={{ params.val_size }}, test_size={{ params.test_size }}
    )
    {{ node_id }}_X_train, {{ node_id }}_X_test = {{ node_id }}_split_res[0], {{ node_id }}_split_res[2]
    {{ node_id }}_y_train, {{ node_id }}_y_test = {{ node_id }}_split_res[3], {{ node_id }}_split_res[5]\
""",

    # Model Nodes
    "train_classification": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_model = train({{ inputs.X_train }}, {{ inputs.y_train }}, task="classification", algorithm="{{ params.algorithm }}")\
""",
    "train_regression": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_model = train({{ inputs.X_train }}, {{ inputs.y_train }}, task="regression", algorithm="{{ params.algorithm }}")\
""",
    "automl": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_res = run_automl({{ inputs.X_train }}, {{ inputs.y_train }}, task="{{ params.task }}", tuning="{{ params.tuning }}", n_trials=10)
    {{ node_id }}_model = {{ node_id }}_res.best_model\
""",

    # Evaluation Nodes
    "evaluate": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_y_pred = {{ inputs.model }}.predict({{ inputs.X_test }})
    {{ node_id }}_metrics = evaluate({{ inputs.y_test }}, {{ node_id }}_y_pred)
    print(f"Metrics ({{ node_id }}): { {{ node_id }}_metrics }")\
""",
    "cross_validate": """\
    # {{ node_label }} ({{ node_id }})
    {{ node_id }}_metrics = cross_validate({{ inputs.X_train }}, {{ inputs.y_train }}, task="{{ params.task }}", algorithm="{{ params.algorithm }}", cv={{ params.cv }})
    print(f"CV Results ({{ node_id }}): { {{ node_id }}_metrics }")\
"""
}

def resolve_input_varnames(node_id: str, connections: List[Dict]) -> Dict[str, str]:
    """
    Given a node_id, map its input ports to the output variable names generated
    by previous nodes block.
    Example return: {"dataframe": "node_1_dataframe"}
    """
    inputs = {}
    for conn in connections:
        if conn["to_node"] == node_id:
            from_node = conn["from_node"]
            from_port = conn["from_port"]
            to_port = conn["to_port"]
            # Enforce the convention used in templates: {node_id}_{port_name}
            inputs[to_port] = f"{from_node}_{from_port}"
    return inputs


def compile_pipeline(pipeline_data: Dict) -> str:
    """
    Compile a DAG structure into a runnable Python script string.
    """
    nodes = pipeline_data.get("nodes", [])
    connections = pipeline_data.get("connections", [])
    
    if not nodes:
        raise PipelineError("Cannot compile an empty pipeline.")

    # Topological sort prevents circular errors and guarantees chronological dependencies.
    execution_order = _topological_sort(nodes, connections)
    node_map = {n["id"]: n for n in nodes}
    
    env = jinja2.Environment(trim_blocks=True, lstrip_blocks=True)
    
    code_blocks = []
    
    for node_id in execution_order:
        node_data = node_map[node_id]
        node_type_id = node_data["type"]
        node_params = node_data.get("params", {})
        
        node_type = get_node_type(node_type_id)
        if not node_type:
            raise PipelineError(f"Node Type '{node_type_id}' is unknown and cannot be compiled.")
        
        if node_type_id not in NODE_TEMPLATES:
            raise PipelineError(f"Node Type '{node_type_id}' is missing a matching Jinja2 compiler template.")
            
        # Get defaults
        for param in node_type.params:
            if param.name not in node_params and param.default is not None:
                node_params[param.name] = param.default
                
        # Resolve what variables mapped into this block
        input_vars = resolve_input_varnames(node_id, connections)
        
        # Verify required inputs are met.
        for port in node_type.inputs:
            if port.name not in input_vars:
                # Add comment but let the script fail predictably
                input_vars[port.name] = "None"
                
        template_str = NODE_TEMPLATES[node_type_id]
        template = env.from_string(template_str)
        
        rendered = template.render(
            node_id=node_id,
            node_label=node_type.label,
            params=node_params,
            inputs=input_vars
        )
        
        code_blocks.append(rendered)
        
    full_code_blocks_str = "\n\n".join(code_blocks)
    
    main_template = env.from_string(BASE_TEMPLATE)
    final_script = main_template.render(code_blocks=full_code_blocks_str)
    
    return final_script
